spring:
    datasource:
        password: root1234
        url: jdbc:mysql://cms-ims.ct9htvyez5bx.us-east-1.rds.amazonaws.com:3306/ims
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        cors:
            allow-credentials: true
            allowed-headers: '*'
            allowed-methods: GET,POST,PUT,DELETE
            allowed-origins: '*'
            max-age: 3600
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
